service: physisBackEnd
package:
  individually: true
  excludeDevDependencies: true

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-aws-alias
  - serverless-pseudo-parameters

custom:
  webpack:
    packager: 'npm'
    packExternalModulesMaxBuffer: 200 * 1024   # Size of stdio buffers for spawned child processes

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  environment:
      USER_TABLE: DevPhysisUser

functions:
  emailExists:
    handler: handlers/emailExisits.checkEmailExists
    events:
      - http:
          path: api/auth/emailExists
          method: get
          cors: true

  getUserData:
    handler: handlers/get_profile_data.getUserData
    events:
      - http:
          path: api/getUserData
          method: get
          cors: true



  updateUserProfile:
    handler: handlers/updateProfile.updateProfile
    events:
      - http:
          path: api/updateUserProfile
          method: put
          cors: true
